#!/usr/bin/python
import argparse
import functools
import logging
import os
import os.path
import re
import sys
import time
import urllib2

import powerpod

LOGGER = logging.getLogger(__name__)

CMD_SPLIT = re.compile(r'(?:[^\\\s]|\\.)+')
WHITESPACE_QUOTE = functools.partial(re.compile(r'(\\s)').sub, r'\\\1')

ACTIONS = {}

def add_action(cls):
	ACTIONS[cls.PARSER.prog] = cls

class Action(object):
	PARSER = NotImplemented
	def __init__(self, extra):
		self.extra = extra

@add_action
class GetAllRidesAction(Action):
	PARSER = argparse.ArgumentParser('get_all_rides', description='Fetch all rides into ride_directory')
	PARSER.add_argument('--no-clobber', dest='existing', action='store_const', const='no_clobber')
	PARSER.add_argument('--force', dest='existing', action='store_const', const='force')
	PARSER.add_argument(
			'--directory',
			dest='directory',
			default='./rides',
	)
	def run(self, protocol, args):
		response = protocol.do_command(powerpod.GetFileListCommand())
		LOGGER.debug(repr(response))
		extra = []
		if self.extra.existing == 'force':
			extra.append('--force')
		elif self.extra.existing == 'no_clobber':
			extra.append('--no-clobber')
		for i, header in enumerate(response.records):
			filepath = os.path.join(self.extra.directory, header.to_filename())
			args.actions.append(make_action("get_ride {} {} {}".format(i, WHITESPACE_QUOTE(filepath), ' '.join(extra))))

@add_action
class ListRidesAction(Action):
	PARSER = argparse.ArgumentParser('list_rides', description='Print information about all rides on the device to stdout')
	def run(self, protocol, args):
		response = protocol.do_command(powerpod.GetFileListCommand())
		LOGGER.debug(repr(response))
		for i, header in enumerate(response.records):
			sys.stdout.write("{} {}\n".format(i, header.to_filename()))

@add_action
class GetRideAction(Action):
	PARSER = argparse.ArgumentParser('get_ride')
	PARSER.add_argument('index', type=int)
	PARSER.add_argument('filename')
	PARSER.add_argument('--no-clobber', dest='existing', action='store_const', const='no_clobber')
	PARSER.add_argument('--force', dest='existing', action='store_const', const='force')
	def run(self, protocol, args):
		time.sleep(1)
		response = protocol.do_command(powerpod.GetFileCommand(self.extra.index))
		filename = self.extra.filename
		if filename is sys.stdout:
			out = sys.stdout
		else:
			if os.path.exists(filename):
				if self.extra.existing == 'force':
					pass
				else:
					if self.extra.existing is None:
						LOGGER.warning('Will not overwrite {!r}; use --force or --no-clobber'.format(filename))
					return
			out = open(filename, 'w')
		LOGGER.info("index=%s header=%s filename=%s", self.extra.index, response.ride_data.get_header(), filename)
		out.write(response.ride_data.to_binary())

@add_action
class EraseAllCommand(Action):
	PARSER = argparse.ArgumentParser('erase_all')
	def run(self, protocol, args):
		protocol.do_command(powerpod.EraseAllCommand())
		rides = protocol.do_command(powerpod.GetFileListCommand())
		assert not rides.size, rides

@add_action
class GetOdometerCommand(Action):
	PARSER = argparse.ArgumentParser('get_odometer')
	def run(self, protocol, args):
		response = protocol.do_command(powerpod.GetOdometerCommand())
		sys.stdout.write('{} km\n'.format(response.distance_km))

@add_action
class GetOdometerCommand(Action):
	PARSER = argparse.ArgumentParser('set_odometer')
	PARSER.add_argument('distance', type=float, help='km rounded to 1 decimal place')
	def run(self, protocol, args):
		distance = round(self.extra.distance, 1)
		if distance != self.extra.distance:
			LOGGER.warning('rounding to one decimal place')
		protocol.do_command(powerpod.SetOdometerCommand(distance))
		response = protocol.do_command(powerpod.GetOdometerCommand())
		assert response.distance_km == distance, response.distance_km

@add_action
class GetFirmwareVersionCommand(Action):
	PARSER = argparse.ArgumentParser('get_firmware_version')
	def run(self, protocol, args):
		response = protocol.do_command(powerpod.GetFirmwareVersionCommand())
		sys.stdout.write('{} {}\n'.format(response.version_encoded, response.version))

@add_action
class GetFirmwareVersionCommand(Action):
	PARSER = argparse.ArgumentParser('check_firmware_version', description="Exits with status 1 if not latest")
	PARSER.add_argument('type', choices=('PwrPod', 'iBike'))
	def run(self, protocol, args):
		response = protocol.do_command(powerpod.GetFirmwareVersionCommand())
		# SUPER PORCELAIN!
		# I think I'm actually meant to read FWstatus.txt, but that is huge and
		# clearly includes much more than the latest version!
		resp = urllib2.urlopen('http://ibikesports.com/iBike_update/')
		resp_content = resp.read()
		versions = re.compile(r'<a href="(PwrPod|iBike)(\d+)\.iBFW3.txt">').findall(resp_content)
		best_version = max(int(version) for type, version in versions if type == self.extra.type)
		if best_version != response.version_encoded:
			sys.stdout.write('{!r} is not latest; {!r} is available\n'.format(response.version_encoded, best_version))
			sys.exit(1)

@add_action
class GetSerialNumberCommand(Action):
	PARSER = argparse.ArgumentParser('get_serial_number')
	def run(self, protocol, args):
		response = protocol.do_command(powerpod.GetSerialNumberCommand())
		sys.stdout.write('{}\n'.format(response.as_hex))

@add_action
class GetSpaceUsageCommand(Action):
	PARSER = argparse.ArgumentParser('get_space_used')
	def run(self, protocol, args):
		response = protocol.do_command(powerpod.GetSpaceUsageCommand())
		sys.stdout.write('{} %\n'.format(response.used_percentage))

def make_action(string):
	parts = CMD_SPLIT.findall(string)
	if not parts:
		raise ValueError("Invalid command {}".format(string))
	if parts[0] not in ACTIONS:
		raise ValueError("Unknown command {}".format(string))
	action_class = ACTIONS[parts[0]]
	args = action_class.PARSER.parse_args(parts[1:])
	return action_class(args)

class HelpActions(argparse.Action):
	def __init__(self, *args, **kwargs):
		kwargs['nargs'] = 0
		super(HelpActions, self).__init__(*args, **kwargs)
	@staticmethod
	def __call__(parser, namespace, values, option_string):
		for action_class in ACTIONS.values():
			action_class.PARSER.print_help()
			sys.stdout.write('\n\n')
		sys.exit(0)

def arg_parser():
	parser = argparse.ArgumentParser()
	parser.add_argument('--port', default='/dev/ttyUSB0')
	parser.add_argument(
			'actions',
			nargs='+',
			type=make_action,
			help="""
				Actions to perform. See --help-actions for a list.
				Parameters to actions must be quoted with the action.
			""",
	)
	parser.add_argument(
			'--help-actions',
			action=HelpActions,
	)
	return parser

def main():
	logging.basicConfig(level=logging.INFO)
	args = arg_parser().parse_args()
	kwargs = {}
	serial_connection = powerpod.NewtonSerialConnection(port=args.port)
	protocol = powerpod.NewtonSerialProtocol(serial_connection, device_side=False)
	for action in args.actions:
		action.run(protocol, args)

if __name__ == '__main__':
	main()
